/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cine;

import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Alumno
 */
public class cines extends javax.swing.JFrame {

    /**
     * Creates new form cines
     */
    public cines() {
        initComponents();
        this.setResizable(false);
        this.setLocation(0, 0);
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cant = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        descuento = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pelis = new javax.swing.JComboBox<>();
        calidad = new javax.swing.JComboBox<>();
        calcular = new javax.swing.JButton();
        comprar = new javax.swing.JButton();
        borrar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        precio = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Snap ITC", 0, 36)); // NOI18N
        jLabel1.setText("CineJUY");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 190, 30));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cantidad de Entradas:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        cant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantActionPerformed(evt);
            }
        });
        cant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cantKeyTyped(evt);
            }
        });
        getContentPane().add(cant, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 57, -1));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel3.setText("Descuento:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        descuento.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        getContentPane().add(descuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 64, 20));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel5.setText("Total:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, -1, -1));

        total.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        getContentPane().add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 40, 14));

        jLabel7.setFont(new java.awt.Font("Tiresias", 0, 18)); // NOI18N
        jLabel7.setText("¿Qué pelicula desea ver?");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 210, -1));

        pelis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Capitana Marvel", "El Manicomio", "Maligno", "El Principe Encantador" }));
        pelis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pelisActionPerformed(evt);
            }
        });
        getContentPane().add(pelis, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 130, -1));

        calidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "2D", "3D", " " }));
        getContentPane().add(calidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 50, -1));

        calcular.setText("Calcular");
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });
        getContentPane().add(calcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        comprar.setText("Comprar");
        comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprarActionPerformed(evt);
            }
        });
        getContentPane().add(comprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, -1, -1));

        borrar.setText("Borrar");
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });
        getContentPane().add(borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, -1, -1));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel4.setText("Precio:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 70, 20));

        precio.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        getContentPane().add(precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 41, 14));

        jLabel9.setFont(new java.awt.Font("Tiresias", 0, 14)); // NOI18N
        jLabel9.setText("Calidad");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cine/0657e2224c552e3-1.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-110, 0, 520, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cantActionPerformed

    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed
        // TODO add your handling code here:
       int [] can= new int[6];
       int canti;
       canti=Integer.parseInt(cant.getText());
       can[0]=1;
       can[1]=2;      
       can[2]=3;
       can[3]=4;
       can[4]=5;
       can[5]=6;
        for (int i = 0; i < can.length; i++) {
            if(can[0]==canti){
                precio.setText("100");
            }
            if(can[1]==canti){
                precio.setText("200");
            }
            if(can[2]==canti){
                precio.setText("300");
            }
            if(can[3]==canti){
                precio.setText("400");
            }
            if(can[4]==canti){
                precio.setText("500");
            }
            if(can[5]==canti){
                precio.setText("600");
            }  
            for (int j = 0; j < can.length; j++) {
                if(canti>2){
                    descuento.setText("20%");
                    int des;
                    int toti=0;
                    int tot;
                    String we;
                   des=Integer.parseInt(precio.getText()); 
                   toti=des*20/100;
                   tot=des-toti;
                   we=String.valueOf(tot);
                   total.setText(we);
                }else{
                    descuento.setText("0");
                    String fi;
                     fi=precio.getText();
                    total.setText(fi);
                }
            }
        }
        
    }//GEN-LAST:event_calcularActionPerformed

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        // TODO add your handling code here:
        pelis.setSelectedIndex(0);
        calidad.setSelectedIndex(0);
        descuento.setText("");
        cant.setText("");
        total.setText("");
        precio.setText("");
        
    }//GEN-LAST:event_borrarActionPerformed

    private void cantKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantKeyTyped
        // TODO add your handling code here:
        char a = evt.getKeyChar();
        if (cant.getText().length() == 1) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
            cant.setText("");
        }

        if (a < '1' || a > '6') {
            evt.consume();

            cant.setText("");
        }
    }//GEN-LAST:event_cantKeyTyped

    private void pelisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pelisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pelisActionPerformed

    private void comprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Compra Exitosa");
    }//GEN-LAST:event_comprarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cines().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrar;
    private javax.swing.JButton calcular;
    private javax.swing.JComboBox<String> calidad;
    private javax.swing.JTextField cant;
    private javax.swing.JButton comprar;
    private javax.swing.JLabel descuento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> pelis;
    private javax.swing.JLabel precio;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
